package com.thuta.trading_backend.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.Data;

import java.time.ZonedDateTime;

@Entity
@Data
public class Coin {

    @Id
    private String id;

    private String symbol;

    private String name;

    private String image;

    @JsonProperty("current_price")
    @Column(name = "current_price")
    private Double currentPrice;

    @JsonProperty("market_cap")
    @Column(name = "market_cap")
    private Long marketCap;

    @JsonProperty("market_cap_rank")
    @Column(name = "market_cap_rank")
    private Integer marketCapRank;

    @JsonProperty("fully_diluted_valuation")
    @Column(name = "fully_diluted_valuation")
    private Long fullyDilutedValuation;

    @JsonProperty("total_volume")
    @Column(name = "total_volume")
    private Long totalVolume;

    @JsonProperty("high_24h")
    @Column(name = "high_24h")
    private Double high24h;

    @JsonProperty("low_24h")
    @Column(name = "low_24h")
    private Double low24h;

    @JsonProperty("price_change_24h")
    @Column(name = "price_change_24h")
    private Double priceChange24h;

    @JsonProperty("price_change_percentage_24h")
    @Column(name = "price_change_percentage_24h")
    private Double priceChangePercentage24h;

    @JsonProperty("market_cap_change_24h")
    @Column(name = "market_cap_change_24h")
    private Long marketCapChange24h;

    @JsonProperty("market_cap_change_percentage_24h")
    @Column(name = "market_cap_change_percentage_24h")
    private Double marketCapChangePercentage24h;

    @JsonProperty("circulating_supply")
    @Column(name = "circulating_supply")
    private Double circulatingSupply;

    @JsonProperty("total_supply")
    @Column(name = "total_supply")
    private Double totalSupply;

    @JsonProperty("max_supply")
    @Column(name = "max_supply")
    private Double maxSupply;

    private Double ath;

    @JsonProperty("ath_change_percentage")
    @Column(name = "ath_change_percentage")
    private Double athChangePercentage;

    @JsonProperty("ath_date")
    @Column(name = "ath_date")
    private ZonedDateTime athDate;

    private Double atl;

    @JsonProperty("atl_change_percentage")
    @Column(name = "atl_change_percentage")
    private Double atlChangePercentage;

    @JsonProperty("atl_date")
    @Column(name = "atl_date")
    private ZonedDateTime atlDate;

    @JsonIgnore
    @Column(name = "roi")
    private String roi;

    @JsonProperty("last_updated")
    @Column(name = "last_updated")
    private ZonedDateTime lastUpdated;

    // Getters and setters (can be generated by your IDE)
}
