export const products = [
  'Wireless Mouse',
  'Mechanical Keyboard',
  'Bluetooth Headphones',
  'Gaming Laptop',
  'USB-C Hub',
  'Ergonomic Office Chair',
  '4K Monitor',
  'Smartphone Tripod',
  'Portable SSD',
  'Noise Cancelling Earbuds',
  'Graphics Tablet',
  'Smartwatch',
  'Adjustable Standing Desk',
  'Gaming Controller',
  'Wireless Charger',
  'External Hard Drive',
  'Smart LED Light Strip',
  'Webcam with Microphone',
  'Multi-Port USB Charger',
  'Laptop Cooling Pad',
  'Fitness Tracker',
  'Smart Home Hub',
  'Wireless Soundbar',
  'VR Headset',
  'Mini Projector',
  'Mechanical Pencil',
  'Notebook with Pen Holder',
  'Action Camera',
  'Rechargeable Battery Pack',
  'Electric Scooter',
  'Digital Drawing Pad',
  'Smart Alarm Clock',
  'USB Microphone',
  'Noise-Isolating Gaming Headset',
  'Foldable Bluetooth Keyboard',
  'Wireless Security Camera',
  'Touchscreen Monitor',
  'Gaming Mouse Pad with RGB',
  'Smartphone Camera Lens Kit',
  'Portable Bluetooth Speaker',
  'Ergonomic Gaming Chair',
  'Selfie Ring Light',
  'Compact Photo Printer',
  'Smart WiFi Plug',
  'Electric Standing Desk',
  'LED Desk Lamp with Wireless Charger',
  '4K Webcam',
  'Multi-Device Bluetooth Mouse',
  'Fast Charging Power Bank',
  'Smart Refrigerator',
  'WiFi Range Extender',
  'Digital Drawing Tablet with Pen',
  'Smart Thermostat',
  'AI Voice Assistant Speaker',
  'Robot Vacuum Cleaner',
  'Gaming Headphones with Surround Sound',
  'Laptop Stand with Cooling Fan',
  'Universal Remote Control',
  'Smart TV Box',
  'Cordless Vacuum Cleaner',
  'Smart Doorbell Camera',
  'USB Flash Drive 1TB',
  'Wireless Bluetooth Earbuds',
  'Multi-Functional Toaster Oven',
  'Gaming Laptop Stand',
  'Fingerprint Smart Lock',
  'Adjustable Cell Phone Stand',
  'Portable Coffee Maker',
  'Smartphone Gimbal Stabilizer',
  'Dash Cam for Car',
  'Compact Mechanical Keyboard',
  'Smart Digital Notebook',
  'Outdoor Security Camera',
  'Solar Power Bank',
  'Wearable Fitness Band',
  'Mini Wireless Keyboard',
  'AI-Powered Translator Device',
  'Streaming Capture Card',
  'USB Hub with HDMI Output',
  'Tablet Stand for Desk',
  'Portable Air Purifier',
  'Digital Smart Scale',
  'Wireless Bluetooth Transmitter',
  'Smart Pet Feeder',
  'Augmented Reality Glasses',
  'Noise-Canceling Office Headphones',
  'USB-C Docking Station',
  'AI-Powered Smart Mirror',
  'Portable Mini Fridge',
  'Multi-Device Charging Station',
  'High-Speed External SSD',
  'Voice-Controlled Smart Lamp',
  'Smart Home Surveillance Kit',
  'Electric Heated Blanket',
  'AI-Powered Language Learning Device',
  'Home Theater Projector',
  'Smart Water Bottle',
  'Wireless Smart Meat Thermometer',
  'Bluetooth Speaker with LED Lights',
  'Automatic Soap Dispenser',
  '3D Printing Pen',
  'Wireless Mechanical Keyboard',
  'Ultra-Thin Laptop Case',
  'Digital Business Card Scanner',
  'Compact Wireless Charger Stand',
]
