name: Compile Java Projects

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [fundamentals]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile ${{ matrix.directory }}
        working-directory: ${{ matrix.directory }}
        run: make compile

      - name: Upload compiled files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.directory }}-compiled
          path: ${{ matrix.directory }}/bin/
