name: Build All Spring Boot Projects

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Find and build all Spring Boot projects
      - name: Build all Spring Boot projects
        run: |
          for dir in $(find . -name "pom.xml" -exec dirname {} \;); do
            echo "Building project in $dir"
            (cd "$dir" && ./mvnw clean install)
          done
